pr:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - apis/poi
    exclude:
    - docs/README.md
      
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - apis/poi


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello World"
  displayName: 'Run a one-line script'

